# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-02 04:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meteoarc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatoMeterologico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('humedadDHT11', models.DecimalField(decimal_places=4, max_digits=10)),
                ('tempDHT11C', models.DecimalField(decimal_places=4, max_digits=10)),
                ('tempDHT11F', models.DecimalField(decimal_places=4, max_digits=10)),
                ('IndCalorDHT11', models.DecimalField(decimal_places=4, max_digits=10)),
                ('altitudMBMP', models.DecimalField(decimal_places=4, max_digits=10)),
                ('altitudFBMP', models.DecimalField(decimal_places=4, max_digits=10)),
                ('tempBMPC', models.DecimalField(decimal_places=4, max_digits=10)),
                ('tempBMPF', models.DecimalField(decimal_places=4, max_digits=10)),
                ('presionAbsMB', models.DecimalField(decimal_places=4, max_digits=10)),
                ('presionAbsInHg', models.DecimalField(decimal_places=4, max_digits=10)),
                ('presionNivelMarMB', models.DecimalField(decimal_places=4, max_digits=10)),
                ('presionNivelMarInHg', models.DecimalField(decimal_places=4, max_digits=10)),
                ('esDia', models.BooleanField()),
                ('velocidadViento', models.DecimalField(decimal_places=4, max_digits=10)),
                ('direccionViento', models.DecimalField(decimal_places=4, max_digits=10)),
                ('cantidadLLuvia', models.DecimalField(decimal_places=4, max_digits=10)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
