# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-03 02:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meteoarc', '0003_auto_20181202_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datometerologico',
            name='direccionViento',
            field=models.CharField(default='Nada', max_length=10),
        ),
    ]
