# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-04 16:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meteoarc', '0004_auto_20181203_0224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datometerologico',
            name='IndCalorDHT11',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='datometerologico',
            name='altitudFBMP',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='datometerologico',
            name='altitudMBMP',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='datometerologico',
            name='cantidadLLuvia',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='datometerologico',
            name='humedadDHT11',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='datometerologico',
            name='presionAbsInHg',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='datometerologico',
            name='presionAbsMB',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='datometerologico',
            name='presionNivelMarInHg',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='datometerologico',
            name='presionNivelMarMB',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='datometerologico',
            name='tempBMPC',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='datometerologico',
            name='tempBMPF',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='datometerologico',
            name='tempDHT11C',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='datometerologico',
            name='tempDHT11F',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='datometerologico',
            name='velocidadViento',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
